version: '1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/local/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
      - ./docker/nginx/local/logs/nginx:/var/log/nginx
      - ./docker/socket:/socket
    container_name: tg_bot_nginx
    depends_on:
      - app
  app:
    build:
      context: docker/app/local
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/socket:/socket
    container_name: tg_bot_app
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    container_name: tg_bot_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tg_bot
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    #      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
