version: '1'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/dev/conf.d:/etc/nginx/conf.d
            - ./:/var/www/html
            - ./docker/nginx/dev/logs/nginx:/var/log/nginx
            - ./docker/socket:/socket
        container_name: tg_bot_nginx
        depends_on:
            - app

    app:
        build:
            context: docker/app/local
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/socket:/socket
        container_name: tg_bot_app
        user: "${UID}:${GID}"
        environment:
            - UID=${UID}
            - GID=${GID}
        depends_on:
            - db

    db:
        image: postgres:latest
        restart: always
        container_name: tg_bot_postgres
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: tg_bot
            POSTGRES_USER: root
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
